name: CI

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:

    name: Deploy to AWS EC2

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go version

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v -o game

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::621271098372:role/davinci-song-game-server-role
          role-session-name: davinci-song-game-server-role

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 400 id_rsa

      - name: Stop service
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.EC2_IP }} 'sudo systemctl stop game.service'          

      - name: Copy binary to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i id_rsa game ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/davinci/game
#          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} 'sudo systemctl restart myapp.service'

      - name: Start service
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.EC2_IP }} 'sudo systemctl start game.service'

